#!/usr/bin/env python3
"""
GPU-Aware Parallel Runner for C-TAEA Replication.

This script distributes the 51 simulations across your 8 GPUs efficiently.
Since the C-TAEA code is CPU-based (NumPy), we use the GPUs' associated
CPU cores to maximize throughput.

Hardware: 8× NVIDIA RTX A6000 (49GB), 64 CPU threads, 1TB RAM

Usage:
    # Run full replication distributed across all 8 GPUs
    python run_parallel_gpu.py --full --gpus 8
    
    # Run with specific GPU assignment (e.g., use GPUs 0,1,2)
    CUDA_VISIBLE_DEVICES=0,1,2 python run_parallel_gpu.py --full --gpus 3
    
    # Quick test on single GPU
    python run_parallel_gpu.py --quick --gpus 1
    
    # Custom configuration
    python run_parallel_gpu.py --problems C1DTLZ3 --m-values 3 5 8 --algos C-TAEA --gpus 8
"""

import os
import sys
import argparse
import subprocess
import json
import time
from pathlib import Path
from datetime import datetime
from typing import List, Dict, Tuple
import multiprocessing

def get_gpu_info() -> Tuple[int, List[int]]:
    """Detect available GPUs and their IDs."""
    try:
        result = subprocess.run(
            ['nvidia-smi', '--query-gpu=index', '--format=csv,noheader'],
            capture_output=True, text=True, check=True
        )
        gpu_ids = [int(x.strip()) for x in result.stdout.strip().split('\n') if x.strip()]
        return len(gpu_ids), gpu_ids
    except Exception as e:
        print(f"Warning: Could not detect GPUs ({e})")
        # Check CUDA_VISIBLE_DEVICES
        cuda_devices = os.environ.get('CUDA_VISIBLE_DEVICES', '')
        if cuda_devices:
            gpu_ids = [int(x.strip()) for x in cuda_devices.split(',') if x.strip()]
            return len(gpu_ids), gpu_ids
        return 0, []

def generate_task_batches(
    n_gpus: int,
    problem_names: List[str],
    m_values: List[int],
    algo_names: List[str],
    n_runs: int
) -> List[List[Dict]]:
    """
    Generate batches of tasks distributed across GPUs.
    Each batch contains configurations for one GPU.
    """
    # Generate all combinations
    all_configs = []
    for prob in problem_names:
        for m in m_values:
            for algo in algo_names:
                all_configs.append({
                    'problem': prob,
                    'm': m,
                    'algo': algo,
                    'n_runs': n_runs
                })
    
    # Distribute across GPUs (round-robin by algorithm for load balancing)
    batches = [[] for _ in range(n_gpus)]
    for i, config in enumerate(all_configs):
        gpu_idx = i % n_gpus
        batches[gpu_idx].append(config)
    
    return batches

def create_gpu_script(gpu_id: int, batch: List[Dict], output_dir: str, workers_per_gpu: int) -> str:
    """Create a Python script for a specific GPU's workload."""
    script = f'''#!/usr/bin/env python3
"""
GPU {gpu_id} Worker Script
Auto-generated by run_parallel_gpu.py
"""

import os
import sys
sys.path.insert(0, '{os.path.dirname(__file__)}')

# Set GPU device
os.environ['CUDA_VISIBLE_DEVICES'] = '{gpu_id}'

# Limit CPU threads for this process (leave some for other GPUs)
os.environ['OMP_NUM_THREADS'] = '{max(1, workers_per_gpu // 2)}'
os.environ['MKL_NUM_THREADS'] = '{max(1, workers_per_gpu // 2)}'
os.environ['NUMEXPR_NUM_THREADS'] = '{max(1, workers_per_gpu // 2)}'

import numpy as np
np.random.seed({gpu_id + 42})

from Experiments.parallel_runner import run_experiment_parallel

# Run configurations for this GPU
configs = {json.dumps(batch)}

results = []
for config in configs:
    print(f"\\n[GPU {gpu_id}] Running {{config['problem']}} m={{config['m']}} {{config['algo']}} ({{config['n_runs']}} runs)")
    
    result = run_experiment_parallel(
        problem_names=[config['problem']],
        m_values=[config['m']],
        algo_names=[config['algo']],
        n_runs=config['n_runs'],
        n_workers={workers_per_gpu},
        output_dir=f'{output_dir}/gpu_{gpu_id}',
        verbose=True,
        batch_size=1
    )
    results.append(result)

print(f"\\n[GPU {gpu_id}] All tasks completed!")
'''
    return script

def run_gpu_worker(gpu_id: int, script_content: str, log_dir: Path) -> subprocess.Popen:
    """Launch a GPU worker process."""
    script_path = log_dir / f'gpu_{gpu_id}_worker.py'
    with open(script_path, 'w') as f:
        f.write(script_content)
    
    log_file = log_dir / f'gpu_{gpu_id}.log'
    
    # Launch the process
    env = os.environ.copy()
    env['CUDA_VISIBLE_DEVICES'] = str(gpu_id)
    
    proc = subprocess.Popen(
        [sys.executable, str(script_path)],
        stdout=open(log_file, 'w'),
        stderr=subprocess.STDOUT,
        env=env
    )
    
    return proc

def monitor_processes(processes: Dict[int, subprocess.Popen], log_dir: Path):
    """Monitor running GPU processes and report progress."""
    print(f"\n{'='*70}")
    print("Monitoring GPU Workers")
    print(f"{'='*70}")
    print(f"Log directory: {log_dir}")
    print(f"Workers: {list(processes.keys())}")
    print(f"\nPress Ctrl+C to stop all workers\n")
    
    try:
        while processes:
            time.sleep(5)
            
            # Check status
            finished = []
            for gpu_id, proc in processes.items():
                ret = proc.poll()
                if ret is not None:
                    status = "✓ COMPLETED" if ret == 0 else f"✗ FAILED (code {ret})"
                    print(f"  [GPU {gpu_id}] {status}")
                    finished.append(gpu_id)
            
            # Remove finished processes
            for gpu_id in finished:
                del processes[gpu_id]
            
            if processes:
                print(f"  Running: {len(processes)} workers remaining...")
                
    except KeyboardInterrupt:
        print("\n\nStopping all workers...")
        for gpu_id, proc in processes.items():
            proc.terminate()
            try:
                proc.wait(timeout=5)
            except subprocess.TimeoutExpired:
                proc.kill()
        print("All workers stopped.")

def merge_results(output_dir: str, n_gpus: int):
    """Merge results from all GPU workers into a single summary."""
    print(f"\n{'='*70}")
    print("Merging Results from All GPUs")
    print(f"{'='*70}")
    
    import json
    import numpy as np
    
    all_results = {}
    
    for gpu_id in range(n_gpus):
        gpu_dir = Path(output_dir) / f'gpu_{gpu_id}'
        if not gpu_dir.exists():
            continue
            
        for json_file in gpu_dir.glob('*.json'):
            with open(json_file, 'r') as f:
                data = json.load(f)
                
            # Extract key info
            if 'problem' in data:
                prob = data['problem']
                m = data['m']
                algo = data['algorithm']
                
                if prob not in all_results:
                    all_results[prob] = {}
                if m not in all_results[prob]:
                    all_results[prob][m] = {}
                
                all_results[prob][m][algo] = data
    
    # Save merged results
    merged_path = Path(output_dir) / 'all_results_merged.json'
    with open(merged_path, 'w') as f:
        json.dump(all_results, f, indent=2)
    
    print(f"Merged results saved to: {merged_path}")
    
    # Print summary
    print("\nSummary:")
    for prob in sorted(all_results.keys()):
        for m in sorted(all_results[prob].keys()):
            for algo in sorted(all_results[prob][m].keys()):
                data = all_results[prob][m][algo]
                igd = data.get('igd_median', 'N/A')
                hv = data.get('hv_median', 'N/A')
                print(f"  {prob:12s} m={m:2d} {algo:12s}: IGD={igd} HV={hv}")

def main():
    parser = argparse.ArgumentParser(
        description='GPU-Aware Parallel Runner for C-TAEA',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Full replication across all 8 GPUs
  python run_parallel_gpu.py --full
  
  # Quick test on single GPU
  python run_parallel_gpu.py --quick --gpus 1
  
  # Specific problems on 4 GPUs
  python run_parallel_gpu.py --problems C1DTLZ1 C1DTLZ3 --m-values 3 5 --gpus 4
        """
    )
    
    parser.add_argument('--full', action='store_true',
                        help='Full replication (51 runs × 11 problems × 5 m × 6 algos)')
    parser.add_argument('--quick', action='store_true',
                        help='Quick test (3 runs, m=3 only)')
    parser.add_argument('--problems', nargs='+',
                        help='Specific problems to run')
    parser.add_argument('--m-values', nargs='+', type=int,
                        help='Specific m values')
    parser.add_argument('--algos', nargs='+',
                        help='Specific algorithms')
    parser.add_argument('--runs', type=int, default=51,
                        help='Runs per configuration (default: 51)')
    parser.add_argument('--gpus', type=int, default=None,
                        help='Number of GPUs to use (default: auto-detect)')
    parser.add_argument('--workers-per-gpu', type=int, default=6,
                        help='Parallel workers per GPU (default: 6, total = 6×8 = 48)')
    parser.add_argument('--output', type=str, default='Results',
                        help='Output directory (default: Results)')
    parser.add_argument('--sequential', action='store_true',
                        help='Run sequentially instead of parallel (for debugging)')
    
    args = parser.parse_args()
    
    # Detect GPUs
    n_gpus_detected, gpu_ids = get_gpu_info()
    n_gpus = args.gpus if args.gpus is not None else n_gpus_detected
    
    if n_gpus == 0:
        print("Warning: No GPUs detected. Running in CPU-only mode.")
        n_gpus = 1
    
    print(f"\n{'#'*70}")
    print(f"# C-TAEA GPU-Aware Parallel Runner")
    print(f"# GPUs: {n_gpus}")
    print(f"# Workers per GPU: {args.workers_per_gpu}")
    print(f"# Total parallel workers: {n_gpus * args.workers_per_gpu}")
    print(f"# Output: {args.output}")
    print(f"{'#'*70}")
    
    # Determine configuration
    if args.full:
        problem_names = [
            'C1DTLZ1', 'C1DTLZ3', 'C2DTLZ2', 'C3DTLZ1', 'C3DTLZ4',
            'DC1DTLZ1', 'DC1DTLZ3', 'DC2DTLZ1', 'DC2DTLZ3', 'DC3DTLZ1', 'DC3DTLZ3'
        ]
        m_values = [3, 5, 8, 10, 15]
        algo_names = ['C-TAEA', 'C-NSGA-III', 'C-MOEA/D', 'C-MOEA/DD', 'I-DBEA', 'CMOEA']
        n_runs = args.runs
    elif args.quick:
        problem_names = ['C1DTLZ1', 'C1DTLZ3', 'C2DTLZ2']
        m_values = [3]
        algo_names = ['C-TAEA', 'C-NSGA-III', 'C-MOEA/D']
        n_runs = 3
    else:
        problem_names = args.problems or ['C1DTLZ3']
        m_values = args.m_values or [3, 5]
        algo_names = args.algos or ['C-TAEA', 'C-NSGA-III']
        n_runs = args.runs
    
    # Calculate workload
    total_configs = len(problem_names) * len(m_values) * len(algo_names)
    total_runs = total_configs * n_runs
    
    print(f"\nWorkload:")
    print(f"  Problems: {problem_names}")
    print(f"  M-values: {m_values}")
    print(f"  Algorithms: {algo_names}")
    print(f"  Runs per config: {n_runs}")
    print(f"  Total configurations: {total_configs}")
    print(f"  Total runs: {total_runs}")
    
    if args.sequential:
        # Run sequentially using the parallel runner directly
        from Experiments.parallel_runner import run_experiment_parallel
        
        run_experiment_parallel(
            problem_names=problem_names,
            m_values=m_values,
            algo_names=algo_names,
            n_runs=n_runs,
            n_workers=n_gpus * args.workers_per_gpu,
            output_dir=args.output,
            verbose=True
        )
    else:
        # Run in parallel across GPUs
        batches = generate_task_batches(n_gpus, problem_names, m_values, algo_names, n_runs)
        
        # Create log directory
        log_dir = Path(args.output) / 'logs'
        log_dir.mkdir(parents=True, exist_ok=True)
        
        # Launch GPU workers
        processes = {}
        for gpu_id in range(n_gpus):
            batch = batches[gpu_id] if gpu_id < len(batches) else []
            if batch:
                script = create_gpu_worker_script(gpu_id, batch, args.output, args.workers_per_gpu)
                proc = run_gpu_worker(gpu_id, script, log_dir)
                processes[gpu_id] = proc
                print(f"  Launched GPU {gpu_id} worker (PID {proc.pid}, {len(batch)} configs)")
        
        # Monitor processes
        monitor_processes(processes, log_dir)
        
        # Merge results
        merge_results(args.output, n_gpus)
    
    print(f"\n{'='*70}")
    print("All tasks completed!")
    print(f"Results saved to: {args.output}/")
    print(f"{'='*70}\n")

if __name__ == '__main__':
    main()
